# .github/workflows/ci.yml
name: CI on Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  build-pr:
    name: Run PR Builds
    uses: ./.github/workflows/build.yml
    with:
      create_universal_app: true
