name: Build and Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*" # Trigger on version tags like v1.0.0

jobs:
  build-linux:
    name: Build for Linux + Windows
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-linux-musl, x86_64-windows]
    steps:
      - uses: actions/checkout@v4

      - name: Install Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.14.1

      - name: Build
        run: |
          zig build -Dtarget=${{ matrix.target }} -Doptimize=ReleaseSafe
          mkdir -p dist
          cp zig-out/bin/panchang-muhurt${{ matrix.target == 'x86_64-windows' && '.exe' || '' }} dist/panchang-muhurt-${{ matrix.target }}${{ matrix.target == 'x86_64-windows' && '.exe' || '' }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: dist/

  build-macos:
    name: Build for macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@v1
        if: runner.os == 'macOS'
        with:
          xcode-version: latest-stable

      - name: Install Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.14.1

      - name: Build
        run: |
          zig build -Doptimize=ReleaseSafe
          mkdir -p dist
          cp zig-out/bin/panchang-muhurt dist/panchang-muhurt-macos

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos
          path: dist/

  release:
    name: Publish GitHub Release
    runs-on: ubuntu-latest
    needs: [build-linux, build-macos]
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/* # Upload all artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
